### PR TITLE
Track .data folder

### LINKED ISSUE #14: hyphy-gui does not run job
screen shot 2018-04-09 at 13 46 58

### PR DESCRIPTION
**Pull request by rdvelazquez**
Closes #14 and #11

### CODE REVIEW

**Comment by rdvelazquez** [comment]
FYI - I'm still looking into what testing frameworks fit best for this codebase. I'll likely push the testing infrastructure along with a very basic/minimal test to get this PR to pass.

**Comment by rdvelazquez** [comment]
I've set up travis to `yarn` and `webpack`. There was an issue when travis was trying to make hyphy (here's the [link](https://travis-ci.org/veg/hyphy-gui/builds/364702432?utm_source=github_status&utm_medium=notification)), so I'm not having it run `make all`. @stevenweaver if you think we should be building hyphy as well I can look into that error further.

I will look to get automated testing set-up in the future but it has been a bit complicated from what I've looked at thus far because the meaningful tests for the GUI will be integration and/or end-to-end tests which are not straight forward with electron, calling hyphy, importing components from vision, etc.

**Comment by stevenweaver** [comment]
It looks like which version of gcc needs to be explicitly stated. Take a look at what I'm doing here : https://github.com/veg/hyphy/blob/master/.travis.yml

**Comment by stevenweaver** [comment]
Changes are still requested.

**Comment by rdvelazquez** [comment]
> It looks like which version of gcc needs to be explicitly stated. Take a look at what I'm doing here : https://github.com/veg/hyphy/blob/master/.travis.yml

I pinned the gcc version in the Makefile (as was done in datamonkey-js).

> Changes are still requested.

I didn't realize I could dismiss someone else's review (which I assume what you wanted me to do?). That's a nice feature... I'll try to not let that power get to my head.

**Comment by stevenweaver** [comment]
@rdvelazquez - Let's remove the `HYPHYMPI` target from hyphy-gui.

**Comment by rdvelazquez** [comment]
> @rdvelazquez - Let's remove the HYPHYMPI target from hyphy-gui.

I think GARD will need MPI right?

**Comment by stevenweaver** [comment]
Yes, but we cannot make having an MPI environment installed a requisite to using the desktop application.

**Comment by rdvelazquez** [comment]
Ok, I'll update my develop branch to remove HYPHYMPI as a target.

**Pull request merged**
